# Generated by Django 4.2.7 on 2023-12-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fathername', models.TextField()),
                ('address', models.TextField()),
                ('big_int', models.BigIntegerField()),
                ('binary_field', models.BinaryField()),
                ('check_field', models.BooleanField()),
                ('date', models.DateField()),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('float', models.FloatField()),
                ('ip_addr', models.GenericIPAddressField()),
                ('img', models.ImageField(upload_to='')),
                ('int', models.IntegerField()),
                ('json_field', models.JSONField()),
                ('positive_int', models.PositiveIntegerField()),
                ('positive_small', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('small_int', models.SmallIntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('url', models.URLField()),
                ('uuid', models.UUIDField()),
            ],
        ),
    ]
